config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    get "/app/views/player" => "player/index#show"
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :contact, only: [:index, :create]
  
  get 'sign/check'
  get 'sign/index'
  get 'gallery/index'
  get 'about/index'
  get 'contact/index'
  get 'player/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :Name,      validate: true
    attribute :Email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :Message
  
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
      {
        :subject => "Contact Form Inquiry",
        :to => "lewiskai0416@gmail.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

    has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def new 
    @contact = Contact.index
  end

  def create
    @contact = Contact.index(params[:Contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message Sent!'
    else
      flash.now[:error] = 'Could not send message!'
      render :contact_index_path
    end
    end
  end
  

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
  end
end

app/controllers/sign_controller.rb
class SignController < ApplicationController
    def index
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/about/index.html.erb
<head>
  <%# about.loading scss%>
  <%= stylesheet_link_tag 'about', 'navbar', 'footer' %>
  <%#Controller about.loading scss%>
  <%= stylesheet_link_tag params[:controller] %>
  <%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
  <%= stylesheet_link_tag "about", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" %>
</head>
<header class="header">
<nav class="navbar">
<div id="logo" style="width: 100%;"> 
    <a href="<%= root_path %>">
        <img class="logo" src="<%= asset_path 'logo.png' %>" />
    </a>
</div>
<ul class="nav-menu">
    <li class="nav-item">
    <a href="<%= player_index_path %>">Project</a>
    </li>
    <li class="nav-item">
        <a href="<%= gallery_index_path %>">Gallery</a>
    </li>
    <li class="nav-item">
        <a href="<%= about_index_path %>">About</a>
    </li>
    <li class="nav-item">
        <a href="<%= contact_index_path %>">Contact</a>
    </li>
</ul>
            <div class="hamburger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
    </header>
<div id="workexperience" class="sectionClass">
    <div class="row ">
      <div class="sectiontitle">
        <h2>About Me</h2>
        <span class="headerLine"></span>
      </div>
      <div class="fullWidth eight columns">
        <ul class="cbp_tmtimeline">
            <li>
                <div class="cbp_tmicon cbp_tmicon-screen">
                    <i class="faPra fa-briefcase"></i>
                </div>
                <div class="cbp_tmlabel wow fadeInRight animated">
                    <h3>Computer Science BSc</h3>
                    <h4><i class="fa fa-flag"></i>University of Surrey, Guildford, Surrey, United Kingdom</h4>
                    <div class="date"><i class="fa fa-calendar"></i>September 2020 - Present</div>
                    <p class="projectParagraph">Currently on 2nd year, Learning Computer Science.</p>
                </div>
            </li>
            <li>
                <div class="cbp_tmicon cbp_tmicon-phone">
                    <i class="faPra fa-briefcase"></i>
                </div>
            <div class="cbp_tmlabel wow fadeInRight animated">
                <h3>Web developer</h3>
            <div class="date">
                <i class="fa fa-calendar"></i>July 2021 - September 2021
            </div>
                <h4><i class="fa fa-flag"></i>M.I.T SKILLS Company, Woking, Surrey, United Kingdom</h4>
                <p class="projectParagraph">Rebuild the whole web system including front and end, UI, Database rebuild and transfer.</p>
            </div>
          </li>
            <li>
            <div class="cbp_tmicon cbp_tmicon-mail">
              <i class="faPra fa-briefcase"></i>
            </div>
            <div class="cbp_tmlabel wow fadeInRight animated">
              <h3>Still Model</h3>
              <h4><i class="fa fa-flag"></i>Ethos Model, London</h4>
              <div class="date"><i class="fa fa-calendar"></i>July 2021 - Present</div>
              <p class="projectParagraph">Currently a model for Still photography</p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <footer class="footer">
    <div class="footer-left">
        <p class="footer-links">
            <a href="<%= root_path %>">Home</a>
            ·
            <a href="<%= player_index_path %>">Project</a>
            ·
            <a href="<%= about_index_path %>">About</a>
            ·
            <a href="<%= contact_index_path %>">Contact</a>
        </p>
        <p class="footer-company-name">JC - Personal Station &copy; 2021</p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>GU1 4AJ</span> Guildford, Surrey, United Kingdom</p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>+44 7720 896787</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:lewiskai0416@gmail.com">lewiskai0416@gmail.com</a></p>
        </div>
    </div>

    <div class="footer-right">
        <p class="footer-company-about">
            <span>About Me</span>
            Computer Science student at University of Surrey.
        </p>
        <div class="footer-icons">
            <a href="https://www.facebook.com/Jimcai20"><i class="fa fa-facebook"></i></a>
            <a href="https://www.instagram.com/lewis_cjm/"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com/lewiskai"><i class="fa fa-github"></i></a>
        </div>
    </div>
</footer>
  <script>
    const hamburger = document.querySelector(".hamburger");
    const navMenu = document.querySelector(".nav-menu");
    const navLink = document.querySelectorAll(".nav-link");

    hamburger.addEventListener("click", mobileMenu);
    navLink.forEach(n => n.addEventListener("click", closeMenu));

    function mobileMenu() {
    hamburger.classList.toggle("active");
    navMenu.classList.toggle("active");
}

    function closeMenu() {
    hamburger.classList.remove("active");
    navMenu.classList.remove("active");
}
    baguetteBox.run('.tz-gallery');
  </script>

app/views/contact/index.html.erb
<head>
  <%# contact.loading scss%>
  <%= stylesheet_link_tag 'contact', 'navbar', 'footer' %>
  <%#Controller contact.loading scss%>
  <%= stylesheet_link_tag params[:controller] %>
  <%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
</head>
<header class="header">
<nav class="navbar">
<div id="logo" style="width: 100%;"> 
    <a href="<%= root_path %>">
        <img class="logo" src="<%= asset_path 'logo.png' %>" />
    </a>
</div>
<ul class="nav-menu">
    <li class="nav-item">
    <a href="<%= player_index_path %>">Project</a>
    </li>
    <li class="nav-item">
        <a href="<%= gallery_index_path %>">Gallery</a>
    </li>
    <li class="nav-item">
        <a href="<%= about_index_path %>">About</a>
    </li>
    <li class="nav-item">
        <a href="<%= contact_index_path %>">Contact</a>
    </li>
</ul>
            <div class="hamburger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
    </header>
<form class="form">
    <h2>CONTACT US</h2>
    <p type="Name:"><input placeholder="Your name"></p>
    <p type="Email:"><input placeholder="e.g: example@gmail.com"></p>
    <p type="Message:"><input placeholder="Please write your message here"></p>
    <button>Send Message</button>
    <div class="info">
      <span class="phone"></span>+44 7720 896787
      <span class="email"></span>lewiskai0416@gmail.com
    </div>
</form>
<footer class="footer" style="margin-top: 30vh; font-family: Georgia, serif;">
    <div class="footer-left">
        <p class="footer-links">
            <a href="<%= root_path %>">Home</a>
            ·
            <a href="<%= player_index_path %>">Project</a>
            ·
            <a href="<%= about_index_path %>">About</a>
            ·
            <a href="<%= contact_index_path %>">Contact</a>
        </p>
        <p class="footer-company-name">JC - Personal Station &copy; 2021</p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>GU1 4AJ</span> Guildford, Surrey, United Kingdom</p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>+44 7720 896787</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:lewiskai0416@gmail.com">lewiskai0416@gmail.com</a></p>
        </div>
    </div>

    <div class="footer-right">
        <p class="footer-company-about">
            <span>About Me</span>
            Computer Science student at University of Surrey.
        </p>
        <div class="footer-icons">
            <a href="https://www.facebook.com/Jimcai20"><i class="fa fa-facebook"></i></a>
            <a href="https://www.instagram.com/lewis_cjm/"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com/lewiskai"><i class="fa fa-github"></i></a>
        </div>
    </div>
</footer>
<script>
const hamburger = document.querySelector(".hamburger");
const navMenu = document.querySelector(".nav-menu");
const navLink = document.querySelectorAll(".nav-link");

hamburger.addEventListener("click", mobileMenu);
navLink.forEach(n => n.addEventListener("click", closeMenu));

function mobileMenu() {
hamburger.classList.toggle("active");
navMenu.classList.toggle("active");
}

function closeMenu() {
hamburger.classList.remove("active");
navMenu.classList.remove("active");
}
baguetteBox.run('.tz-gallery');
</script>

app/views/gallery/index.html.erb
<head>
  <%# gallery.loading scss css%>
  <%= stylesheet_link_tag 'gallery', 'navbar', 'footer', 'bagBox.min', 'bootstrap.min' %>
  <%#Controller gallery.loading scss%>
  <%= stylesheet_link_tag params[:controller] %>
  <%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
</head>
<header class="header">
<nav class="navbar">
<div id="logo" style="width: 100%;"> 
    <a href="<%= root_path %>">
        <img class="logo" src="<%= asset_path 'logo.png' %>" />
    </a>
</div>
<ul class="nav-menu">
    <li class="nav-item">
    <a href="<%= player_index_path %>">Project</a>
    </li>
    <li class="nav-item">
        <a href="<%= gallery_index_path %>">Gallery</a>
    </li>
    <li class="nav-item">
        <a href="<%= about_index_path %>">About</a>
    </li>
    <li class="nav-item">
        <a href="<%= contact_index_path %>">Contact</a>
    </li>
</ul>
            <div class="hamburger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
    </header>

<div class="container gallery-container">

    <h1>My Life Gallery</h1>

    <p class="page-description text-center">All of the views and memories has been taken by my camera.</p>
    
    <div class="tz-gallery">

        <div class="row">
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '41.jpg' %>" />
                    <img src="<%= asset_path '41.jpg' %>" alt="London">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '42.jpg' %>" />
                    <img src="<%= asset_path '42.jpg' %>" alt="London">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '47.jpg' %>" />
                    <img src="<%= asset_path '47.jpg' %>" alt="Bristol">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '44.jpg' %>" />
                    <img src="<%= asset_path '44.jpg' %>" alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '45.jpg' %>" />
                    <img src="<%= asset_path '45.jpg' %>" / alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '46.jpg' %>" />
                    <img src="<%= asset_path '46.jpg' %>" alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '49.jpg' %>" />
                    <img src="<%= asset_path '49.jpg' %>" alt="Buxton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '60.jpg' %>" />
                    <img src="<%= asset_path '60.jpg' %>" alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '61.jpg' %>" />
                    <img src="<%= asset_path '61.jpg' %>" alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '62.jpg' %>" />
                    <img src="<%= asset_path '62.jpg' %>" alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '48.jpg' %>" />
                    <img src="<%= asset_path '48.jpg' %>" alt="Bristol">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '58.jpg' %>" />
                    <img src="<%= asset_path '58.jpg' %>" alt="Guildford">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '59.jpg' %>" />
                    <img src="<%= asset_path '59.jpg' %>" alt="Guildford">
                </a>
            </div>

            <div class="col-sm-12 col-md-4">
                <a class="lightbox" href="<%= asset_path '43.jpg' %>" />
                    <img src="<%= asset_path '43.jpg' %>" alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '51.jpg' %>" />
                    <img src="<%= asset_path '51.jpg' %>" alt="Guildford">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '52.jpg' %>" />
                    <img src="<%= asset_path '52.jpg' %>" alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '53.jpg' %>" />
                    <img src="<%= asset_path '53.jpg' %>" alt="Brighton">
                </a>
            </div>
            <div class="col-sm-6 col-md-4">
                <a class="lightbox" href="<%= asset_path '50.jpg' %>" />
                    <img src="<%= asset_path '50.jpg' %>" alt="Guildford">
                </a>
            </div>
        </div>

    </div>

</div>
<footer class="footer" style="margin-top: 20vh;">
    <div class="footer-left">
        <p class="footer-links">
            <a href="<%= root_path %>">Home</a>
            ·
            <a href="<%= player_index_path %>">Project</a>
            ·
            <a href="<%= about_index_path %>">About</a>
            ·
            <a href="<%= contact_index_path %>">Contact</a>
        </p>
        <p class="footer-company-name">JC - Personal Station &copy; 2021</p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>GU1 4AJ</span> Guildford, Surrey, United Kingdom</p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>+44 7720 896787</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:lewiskai0416@gmail.com">lewiskai0416@gmail.com</a></p>
        </div>
    </div>

    <div class="footer-right">
        <p class="footer-company-about">
            <span>About Me</span>
            Computer Science student at University of Surrey.
        </p>
        <div class="footer-icons">
            <a href="https://www.facebook.com/Jimcai20"><i class="fa fa-facebook"></i></a>
            <a href="https://www.instagram.com/lewis_cjm/"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com/lewiskai"><i class="fa fa-github"></i></a>
        </div>
    </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script src="https://github.com/lewiskai/JC-Portfolio/blob/4fffc7670c027144d7c1644bff273f8eb7398ad7/scripts/gallery.js"></script>
<script>
        const hamburger = document.querySelector(".hamburger");
        const navMenu = document.querySelector(".nav-menu");
        const navLink = document.querySelectorAll(".nav-link");

        hamburger.addEventListener("click", mobileMenu);
        navLink.forEach(n => n.addEventListener("click", closeMenu));

        function mobileMenu() {
            hamburger.classList.toggle("active");
            navMenu.classList.toggle("active");
        }

        function closeMenu() {
            hamburger.classList.remove("active");
            navMenu.classList.remove("active");
        }
        baguetteBox.run('.tz-gallery');
</script>

app/views/home/index.html.erb
<%= stylesheet_link_tag 'home', 'footer', media: 'all', 'data-turbolinks' => true %>
<%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
<header class="nav-bar">
        <div id="logo" style="width: 100%;"> 
            <a href="<%= root_path %>">
                <img class="logo" src="<%= asset_path 'logo.png' %>" />
            </a>
        </div>
        <ul class="nav-list" id="navi-list">
            <li class="list-item">
                <a href="<%= player_index_path %>">Project</a>
            </li>
            <li class="list-item">
            <a href="<%= gallery_index_path %>">Gallery</a>
            </li>
            <li class="list-item">
            <a href="<%= about_index_path %>">About</a>
            </li>
            <li class="list-item">
                <a href="<%= contact_index_path %>">Contact</a>
            </li>
        </ul>
        <div class="menu" id="toggle-Button">
            <div class="menu-line"></div>
            <div class="menu-line"></div>
            <div class="menu-line"></div>
        </div>
    </header>
    <section class="banner">
        <div class="textBx">
            <h2>Hello, Here is<br><span>Jim.</span></h2>
            <h3>A Computer Science Student From University of Surrey</h3>
            <a href="<%= about_index_path %>" class="btn">About Me</a>
        </div>
    </section>
    <footer class="footer">
    <div class="footer-left">
        <p class="footer-links">
            <a href="<%= root_path %>">Home</a>
            ·
            <a href="<%= player_index_path %>">Project</a>
            ·
            <a href="<%= about_index_path %>">About</a>
            ·
            <a href="<%= contact_index_path %>">Contact</a>
        </p>
        <p class="footer-company-name">JC - Personal Station &copy; 2021</p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>GU1 4AJ</span> Guildford, Surrey, United Kingdom</p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>+44 7720 896787</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:lewiskai0416@gmail.com">lewiskai0416@gmail.com</a></p>
        </div>
    </div>

    <div class="footer-right">
        <p class="footer-company-about">
            <span>About Me</span>
            Computer Science student at University of Surrey.
        </p>
        <div class="footer-icons">
            <a href="https://www.facebook.com/Jimcai20"><i class="fa fa-facebook"></i></a>
            <a href="https://www.instagram.com/lewis_cjm/"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com/lewiskai"><i class="fa fa-github"></i></a>
        </div>
    </div>
</footer>
    <script>
        const toggleButton = document.getElementById('toggle-Button');
        const naviList = document.getElementById('navi-list');
    
        toggleButton.addEventListener('click', () => {
            naviList.classList.toggle('active');
        })
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JC - Personal Station</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sign/check.html.erb
<% if signed_in? %>
Signed in as: <%= current_user.email %>
<%= button_to 'Sign out', sign_out_path, method: :delete %>
<% else %>
<%= link_to 'Sign in', sign_in_path %>
<% end %>

<div id="flash">
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>
</div>

app/views/sign/index.html.erb
<head>
  <%# sign.loading scss css%>
  <%= stylesheet_link_tag 'sign', 'footer' %>
  <%#Controller sign.loading scss%>
  <%= stylesheet_link_tag params[:controller] %>
  <%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
</head>
<div class="container" id="container">
    <div class="login-content">
        <form>
        <h1 class="title">Welcome</h1>
        <div class="input-div name">
            <div class="input">
                <i class="fas fa-user"></i>
            </div>
            <div class="div">
                <h5>Username</h5>
                <input type="text" class="input" required>
            </div>
        </div>
        <div class="input-div pass">
            <div class="input">
                <i class="fas fa-lock"></i>
            </div>
            <div class="div">
                <h5>Password</h5>
                <input type="password" class="inputpass" required>
            </div>
            <a href="#">Forgot Password?</a>
            <input type="Submit" class="botton" value="Login">
        </form>
    </div>
</div>

<footer class="footer">
    <div class="footer-left">
        <p class="footer-links">
            <a href="<%= root_path %>">Home</a>
            ·
            <a href="<%= player_index_path %>">Project</a>
            ·
            <a href="<%= about_index_path %>">About</a>
            ·
            <a href="<%= contact_index_path %>">Contact</a>
        </p>
        <p class="footer-company-name">JC - Personal Station &copy; 2021</p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>GU1 4AJ</span> Guildford, Surrey, United Kingdom</p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>+44 7720 896787</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:lewiskai0416@gmail.com">lewiskai0416@gmail.com</a></p>
        </div>
    </div>

    <div class="footer-right">
        <p class="footer-company-about">
            <span>About Me</span>
            Computer Science student at University of Surrey.
        </p>
        <div class="footer-icons">
            <a href="https://www.facebook.com/Jimcai20"><i class="fa fa-facebook"></i></a>
            <a href="https://www.instagram.com/lewis_cjm/"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com/lewiskai"><i class="fa fa-github"></i></a>
        </div>
    </div>
</footer>
<script>
    const inputs = document.querySelectorAll(".input");

    function addcl()
    {
        let parent = this.parentNode.parentNode;
        parent.classList.add("focus");
    }

    function remcl()
    {
        let parent = this.parentNode.parentNode;
        if (this.value == "") {
            parent.classList.remove("focus");
        }
    }

    inputs.forEach(input => 
    {
        input.addEventListener("focus", addcl);
        input.addEventListener("blur", remcl);
    }   
);
</script>